### ISSUE TITLE
Broken concept

### ISSUE THREAD

**Issue by sgalinski** [haassie/rh_recaptcha#7]
The extension doesn't works as a spam protection in it's current state. You can simply remove the whole recaptcha code from the rendered form and powermail accepts it without any problems.

**Comment by sgalinski** [comment]
This zip contains the fixed extension. Also contains a couple of other features like the support of multiple forms on on page with own recaptcha implementations.

[rh_recaptcha_0.1.1_201606162059.zip](https://github.com/haassie/rh_recaptcha/files/319126/rh_recaptcha_0.1.1_201606162059.zip)

**Comment by sgalinski** [comment]
Not tested on powermail 3!

**Comment by haassie** [comment]
Currently i'm not able to really check the code, but I am in a week or 4. I definitely will check the code and implement it when it solves that problem.

Thanks for your feedback and solution!

**Comment by danielkuehni** [comment]
I modified sgalinskis version to work with powermail 3.
This version doesn't work on powermail v2 because tablenames changed.

[rh_recaptcha_powermail_3.zip](https://github.com/haassie/rh_recaptcha/files/341800/rh_recaptcha_powermail_3.zip)

**Comment by ursbraem** [comment]
I installed the fixed version from @sgalinski in TYPO3 6.2.26 with Powermail 2.5.0 and got this error: 

`Could not load partial file. Tried following paths: "/home/user/public_html/projekte/typo3conf/ext/rh_recaptcha/Resources/Private/Partials/PowermailAll/Mail.html", "/home/user/public_html/projekte/typo3conf/ext/rh_recaptcha/Resources/Private/Partials/PowermailAll/Mail".

More information regarding this error might be available online.`

https://wiki.typo3.org/Exception/CMS/1298012500

But that's probably because the powermail version is old, right?

**Comment by haassie** [comment]
That's correct. In the new version I will add a constraint to the powermail
version.

Kind regards,

Richard

Op maandag 8 augustus 2016 heeft Urs Braem notifications@github.com het
volgende geschreven:

**Comment by ursbraem** [comment]
Yes, I've updated powermail and now it works! Thanks & sorry for the noise :-)

**Comment by haassie** [comment]
This is fixed in version 1.0
